apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfov2
spec:
  selector:
    matchLabels:
      app: podinfov2
  template:
    metadata:
      labels:
        app: podinfov2
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "workshop:podinfov2"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP