version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting install `date`
      - VERSION="v2.9.0-beta.3"

  build:
    commands:
      - echo Build started on `date`
      - echo Scanning with horusec...
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src public.ecr.aws/roxsross/horusec:$VERSION horusec start -p /src -P "$(pwd)" -e="true" -o="json" -O=src/horusec.json || true

  post_build:
    commands:
      - echo Build completed on `date`
      - wget --quiet https://roxsross-linktree.s3.amazonaws.com/horusec_vulnerability.py
      - python horusec_vulnerability.py
artifacts:
  files: horusec.json